name: emscripten CI

env:
  EM_VERSION: 3.1.1
  EM_CACHE_FOLDER: 'emsdk-cache'

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}
    - uses: wcwac/setup-emsdk@v11
      with:
        version: ${{env.EM_VERSION}}
        update-tags: true
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
    - name: check
      run: emcc -v
    - name: make
      run: make
    - name: move output files
      run: |
        mkdir output
        mv onscripter.* output
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: output # The folder the action should deploy.
    - uses: actions/upload-artifact@v2
      with:
        path: output
